---
name: mqwf

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]

defaults:
  run:
    shell: bash

jobs:
  fast:
    runs-on: ubuntu-latest

    steps:
    - name: Something fast
      run: |
        hostname

  slow:
    if: contains(github.event_name, 'merge_group')
    runs-on: ubuntu-latest

    steps:
    - name: Something slow
      run: |
        sleep 10
        hostname

  slow2:
    if: contains(github.event_name, 'merge_group')
    runs-on: ubuntu-latest

    steps:
    - name: Something slow
      run: |
        sleep 10
        hostname
        afadfs
