---
name: mqwf

on:
  push:
    branches: [main, next]
    tags: ["v*"]
  pull_request:
    branches: [main, next]
  merge_group:
    branches: [main, next]
    types: [checks_requested]

defaults:
  run:
    shell: bash

jobs:
  fast:
    runs-on: ubuntu-latest

    steps:
    - name: Something fast
      run: |
        hostname

  slow:
    runs-on: ubuntu-latest

    steps:
    - name: Something slow
      run: |
        sleep 10
        hostname
