---
name: mqwf

on:
  push:
  pull_request:
  merge_group:

defaults:
  run:
    shell: bash

jobs:
  fast:
    runs-on: ubuntu-latest

    steps:
    - name: Something fast
      run: |
        hostname

  slow:
    runs-on: ubuntu-latest

    steps:
    - name: Something slow
      run: |
        sleep 10
        hostname
