---
name: mqwf

on:
  push:
    branches: ["*queue*main*"]
  pull_request:
    branches: [main]
  merge_group:

defaults:
  run:
    shell: bash

jobs:
  fast:
    runs-on: ubuntu-latest

    steps:
    - name: Something fast
      run: |
        hostname

  slow:
    if: (github.event_name == 'merge_group')
    runs-on: ubuntu-latest

    steps:
    - name: Something slow
      run: |
        sleep 10
        hostname
